---
blank_issues_enabled: false
contact_links:
  - name: wolfwarrior.dev Community Support
    url: https://github.com/WolFWarr1oR/wolfwarrior.dev/discussions
    about: Please ask and answer questions here.
